
###
GET http://localhost:8084/manage/health


###
POST http://localhost:8082/api/microservicio-historias-clinicas/historias-clinicas
Content-Type: application/json

{
    "amnesis":"amnesis120624",
    "antecedentesFamiliares":"",
    "antecedentesGinecoobstetricos":"",
    "antecedentesNoPatologicos":"",
    "antecedentesPatologicos":"",
    "antecedentesPersonales":"",
    "diagnosticoPresuntivo":"",
    "diagnosticosDiferenciales":"",
    "examenFisico":"",
    "examenFisicoEspecial":"",
    "propuestaBasicaDeConducta":"",
    "tratamiento":"tratamiento1",
    "idPaciente":2,
    "idMedico":2,
    "idEspecialidad":2
}
###
PUT http://localhost:8082/api/microservicio-historias-clinicas/historias-clinicas/8
Content-Type: application/json

{
    "amnesis":"nombre amnesis 1",
    "antecedentesFamiliares":"",
    "antecedentesGinecoobstetricos":"",
    "antecedentesNoPatologicos":"",
    "antecedentesPatologicos":"",
    "antecedentesPersonales":"",
    "diagnosticoPresuntivo":"",
    "diagnosticosDiferenciales":"",
    "examenFisico":"",
    "examenFisicoEspecial":"",
    "propuestaBasicaDeConducta":"",
    "tratamiento":"tratamiento1",
    "idPaciente":1,
    "idMedico":1,
    "idEspecialidad":1
}
###
GET http://localhost:8082/api/microservicio-historias-clinicas/historias-clinicas/paciente/2
###
GET http://localhost:8082/api/microservicio-historias-clinicas/historias-clinicas/1
###
GET http://localhost:8082/api/microservicio-historias-clinicas/historias-clinicas

###
GET http://localhost:8082/api/microservicio-historias-clinicas/historias-clinicas/info-container

###
GET http://localhost:8082/api/microservicio-historias-clinicas/manage/health



#consultas-medicas-lb
#consultas-medicas-sg
#consultas-medicas-tg

# Notas evolucion--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

###
GET http://localhost:8082/api/microservicio-historias-clinicas/manage/health


###
GET http://localhost:8082/api/microservicio-historias-clinicas/notas-evolucion/1

###
GET http://localhost:8082/api/microservicio-historias-clinicas/notas-evolucion


###
GET http://localhost:8082/api/microservicio-historias-clinicas/notas-evolucion/paciente/2

###
GET http://localhost:8082/api/microservicio-historias-clinicas/notas-evolucion/info-container

###
POST http://localhost:8082/api/microservicio-historias-clinicas/notas-evolucion
Content-Type: application/json

{
    "cambiosPacienteResultadosTratamiento":"nota evolucion 05062024",
    "idMedico":2,
    "idHistoriaClinica":1
}
###
PUT http://localhost:8082/api/microservicio-historias-clinicas/notas-evolucion/12
Content-Type: application/json

{
    "cambiosPacienteResultadosTratamiento":" 05062024 actualizado",
    "idMedico":2,
    "idHistoriaClinica":1
}
