spring:
    datasource:
        url: jdbc:mysql://${IP:localhost}:${PORT:3306}/${DATABASE:gestion-consultas-externas}
        username: root
        password: admin
        show-sql: true
server:
  port: 8082